export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const CREATE_INCIDENT = 'CREATE_INCIDENT'
export const CREATE_INCIDENT_SUCCESS = 'CREATE_INCIDENT_SUCCESS'
export const CREATE_INCIDENT_FAIL = 'CREATE_INCIDENT_FAIL'
